service: lambda-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: ./src/functions/index.handler
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline
